# Generated by Django 5.1.4 on 2025-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_rename_sizefk_paper_sizefk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryindextable',
            name='type',
            field=models.CharField(choices=[('COLOR', '색상'), ('THEME', '테마'), ('SIZE', '사이즈'), ('RATIO', '비율')], max_length=10),
        ),
    ]
