# Generated by Django 5.1.4 on 2025-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identifyCode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
