# Generated by Django 5.1.4 on 2025-02-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_identifycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="provider",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
